[package]
name = "datagen"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Whiting, Viren & The Monty Authors"]

[dependencies]
monty = { path = "../", features = ["datagen"] }
montyformat = "0.9.2"

[features]
default = []
value   = ["monty/value"]
policy  = ["monty/policy"]
