name: Build Binary

on:
  push:
    branches:
      - '**'  # Triggers on all branches
  pull_request:
    branches:
      - '**'  # Triggers on all branches

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install build dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install build-essential -y

    - name: Install Make on Windows
      if: matrix.os == 'windows-latest'
      run: choco install make

    - name: Run Make
      run: make

    - name: Get Bench
      run: ./monty bench

