name: Checks

on:
    pull_request:
    push:
      branches:
        - main

jobs:
  check-clippy-test:
    name: check-clippy-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["datagen", "montyformat", "monty"]
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
          with:
            components: clippy
        - run: cargo check --package ${{ matrix.package }}
        - run: cargo clippy --package ${{ matrix.package }}
        - run: cargo test --package ${{ matrix.package }}

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
          with:
            components: rustfmt
        - run: cargo fmt -- --check

