name: Checks

on:
    push:
      branches:
        - master
    pull_request:

jobs:
  check-clippy-test:
    name: check-clippy-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["datagen", "montyformat", "monty", "train-value"]
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
          with:
            components: clippy
        - name: Set feature flags for "train-value"
          if: matrix.package == 'train-value'
          run: echo "FEATURE_FLAGS=--features cpu --no-default-features" >> $GITHUB_ENV
        - name: cargo check
          run: cargo check --package ${{ matrix.package }} $FEATURE_FLAGS
        - name: cargo clippy
          run: cargo clippy --package ${{ matrix.package }} $FEATURE_FLAGS
        - name: cargo test
          run: cargo test --package ${{ matrix.package }} $FEATURE_FLAGS

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
          with:
            components: rustfmt
        - run: cargo fmt -- --check

