name: Rustfmt
on:
  pull_request_target:
    branches:
      - "master"
    paths:
      - "**.rs"

permissions:
  pull-requests: write

jobs:
  Rustfmt:
    name: Rustfmt
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run rustfmt style check
        uses: actions-rs/cargo@v1
        id: rustfmt
        with:
          command: fmt
          args: --check
        continue-on-error: true

      - name: Comment on PR if rustfmt fails
        if: steps.rustfmt.outcome == 'failure'
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # @v2.5.0
        with:
          message: |
            rustfmt needs to be run on this PR.
            If you do not have rustfmt installed, you can install it with `rustup component add rustfmt`.
            For the exact version please see the [rustfmt documentation](https://github.com/rust-lang/rustfmt).

            _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
          comment_tag: execution
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR if rustfmt passes
        if: steps.rustfmt.outcome != 'failure'
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # @v2.5.0
        with:
          message: |
            _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
          create_if_not_exists: false
          comment_tag: execution
          mode: delete
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
